-- Sample players for rehearsals. NOT a migration: apply manually to a
-- practice project (or locally), then delete them from the admin page.
insert into public.players (name, pool, role, batting_style, bowling_style, grade, base_price, notes) values
  ('Yash Kulkarni', 'men', 'Bowler', 'Left-hand bat', 'Right-arm fast', 'A', 50, 'Sample player'),
  ('Om Sharma', 'men', 'All-rounder', 'Left-hand bat', 'Right-arm medium', 'A', 50, 'Sample player'),
  ('Rahul Patil', 'men', 'Batter', 'Right-hand bat', NULL, 'B', 30, 'Sample player'),
  ('Dhruv Rao', 'men', 'Bowler', 'Right-hand bat', 'Left-arm orthodox', 'C', 20, 'Sample player'),
  ('Dhruv Sharma', 'men', 'Bowler', 'Right-hand bat', 'Left-arm orthodox', 'A', 50, 'Sample player'),
  ('Harsh Patil', 'men', 'Bowler', 'Right-hand bat', 'Left-arm medium', 'C', 20, 'Sample player'),
  ('Om Mehta', 'men', 'Bowler', 'Right-hand bat', 'Right-arm fast', 'B', 30, 'Sample player'),
  ('Tanmay Joshi', 'men', 'Bowler', 'Left-hand bat', 'Right-arm leg-spin', 'B', 30, 'Sample player'),
  ('Om Bhat', 'men', 'Bowler', 'Right-hand bat', 'Left-arm medium', 'B', 30, 'Sample player'),
  ('Arjun Mehta', 'men', 'Batter', 'Left-hand bat', 'Right-arm off-spin', 'B', 30, 'Sample player'),
  ('Siddharth Mehta', 'men', 'Wicket-keeper', 'Right-hand bat', NULL, 'A', 50, 'Sample player'),
  ('Karan Reddy', 'men', 'Batter', 'Left-hand bat', 'Right-arm off-spin', 'C', 20, 'Sample player'),
  ('Nikhil Mehta', 'men', 'Bowler', 'Right-hand bat', 'Right-arm fast', 'C', 20, 'Sample player'),
  ('Kunal Nair', 'men', 'All-rounder', 'Left-hand bat', 'Left-arm orthodox', 'A', 50, 'Sample player'),
  ('Om Rao', 'men', 'All-rounder', 'Left-hand bat', 'Right-arm off-spin', 'B', 30, 'Sample player'),
  ('Aarav Nair', 'men', 'Bowler', 'Right-hand bat', 'Left-arm orthodox', 'C', 20, 'Sample player'),
  ('Aditya Shinde', 'men', 'Batter', 'Left-hand bat', 'Right-arm off-spin', 'C', 20, 'Sample player'),
  ('Karan Patil', 'men', 'Batter', 'Right-hand bat', 'Right-arm off-spin', 'B', 30, 'Sample player'),
  ('Rahul Pawar', 'men', 'Bowler', 'Left-hand bat', 'Right-arm leg-spin', 'C', 20, 'Sample player'),
  ('Dhruv Kulkarni', 'men', 'Batter', 'Right-hand bat', NULL, 'A', 50, 'Sample player'),
  ('Karan Pawar', 'men', 'Bowler', 'Right-hand bat', 'Right-arm fast', 'B', 30, 'Sample player'),
  ('Rahul Gupta', 'men', 'Bowler', 'Right-hand bat', 'Left-arm medium', 'C', 20, 'Sample player'),
  ('Varun Bhat', 'men', 'All-rounder', 'Left-hand bat', 'Left-arm orthodox', 'C', 20, 'Sample player'),
  ('Pranav Reddy', 'men', 'Bowler', 'Right-hand bat', 'Left-arm orthodox', 'B', 30, 'Sample player'),
  ('Aditya Patil', 'men', 'Wicket-keeper', 'Left-hand bat', NULL, 'B', 30, 'Sample player'),
  ('Tanmay Sharma', 'men', 'Batter', 'Left-hand bat', NULL, 'C', 20, 'Sample player'),
  ('Arjun Pawar', 'men', 'Batter', 'Left-hand bat', 'Right-arm off-spin', 'B', 30, 'Sample player'),
  ('Tanmay Iyer', 'men', 'Bowler', 'Left-hand bat', 'Left-arm orthodox', 'A', 50, 'Sample player'),
  ('Karan Nair', 'men', 'Batter', 'Left-hand bat', 'Right-arm off-spin', 'A', 50, 'Sample player'),
  ('Ishaan Gupta', 'men', 'Batter', 'Right-hand bat', 'Right-arm off-spin', 'C', 20, 'Sample player'),
  ('Harsh Bhat', 'men', 'Batter', 'Left-hand bat', NULL, 'B', 30, 'Sample player'),
  ('Manav Iyer', 'men', 'All-rounder', 'Left-hand bat', 'Right-arm medium', 'B', 30, 'Sample player'),
  ('Dhruv Mehta', 'men', 'All-rounder', 'Right-hand bat', 'Right-arm medium', 'C', 20, 'Sample player'),
  ('Pranav Kale', 'men', 'All-rounder', 'Left-hand bat', 'Right-arm off-spin', 'A', 50, 'Sample player'),
  ('Aarav Sharma', 'men', 'All-rounder', 'Left-hand bat', 'Right-arm medium', 'B', 30, 'Sample player'),
  ('Varun Shinde', 'men', 'Wicket-keeper', 'Right-hand bat', NULL, 'C', 20, 'Sample player'),
  ('Dhruv Patil', 'men', 'Batter', 'Left-hand bat', NULL, 'A', 50, 'Sample player'),
  ('Tanmay Bhat', 'men', 'Bowler', 'Right-hand bat', 'Right-arm leg-spin', 'A', 50, 'Sample player'),
  ('Kabir Bhat', 'men', 'Bowler', 'Left-hand bat', 'Left-arm medium', 'C', 20, 'Sample player'),
  ('Ishaan Reddy', 'men', 'All-rounder', 'Left-hand bat', 'Left-arm orthodox', 'B', 30, 'Sample player'),
  ('Varun Reddy', 'men', 'All-rounder', 'Right-hand bat', 'Right-arm medium', 'A', 50, 'Sample player'),
  ('Rohan Sharma', 'men', 'Batter', 'Left-hand bat', NULL, 'C', 20, 'Sample player'),
  ('Nikhil Kulkarni', 'men', 'Bowler', 'Right-hand bat', 'Right-arm fast', 'A', 50, 'Sample player'),
  ('Manav Kale', 'men', 'Wicket-keeper', 'Right-hand bat', NULL, 'B', 30, 'Sample player'),
  ('Aarav Deshpande', 'men', 'Batter', 'Left-hand bat', 'Right-arm off-spin', 'B', 30, 'Sample player'),
  ('Harsh Reddy', 'men', 'All-rounder', 'Left-hand bat', 'Left-arm orthodox', 'A', 50, 'Sample player'),
  ('Varun Rao', 'men', 'Bowler', 'Right-hand bat', 'Left-arm orthodox', 'C', 20, 'Sample player'),
  ('Harsh Kulkarni', 'men', 'Bowler', 'Right-hand bat', 'Left-arm orthodox', 'A', 50, 'Sample player'),
  ('Rohan Kulkarni', 'men', 'Batter', 'Right-hand bat', NULL, 'C', 20, 'Sample player'),
  ('Yash Rao', 'men', 'Bowler', 'Right-hand bat', 'Right-arm fast', 'B', 30, 'Sample player'),
  ('Dhruv Joshi', 'men', 'Batter', 'Right-hand bat', 'Right-arm off-spin', 'C', 20, 'Sample player'),
  ('Arjun Nair', 'men', 'Batter', 'Left-hand bat', NULL, 'C', 20, 'Sample player'),
  ('Varun Gupta', 'men', 'Bowler', 'Left-hand bat', 'Left-arm medium', 'B', 30, 'Sample player'),
  ('Aditya Pawar', 'men', 'Bowler', 'Left-hand bat', 'Left-arm orthodox', 'B', 30, 'Sample player'),
  ('Yash Patil', 'men', 'All-rounder', 'Left-hand bat', 'Right-arm medium', 'B', 30, 'Sample player'),
  ('Rohan Kale', 'men', 'Bowler', 'Right-hand bat', 'Right-arm leg-spin', 'B', 30, 'Sample player'),
  ('Varun Joshi', 'men', 'All-rounder', 'Right-hand bat', 'Right-arm off-spin', 'A', 50, 'Sample player'),
  ('Pranav Iyer', 'men', 'Bowler', 'Left-hand bat', 'Right-arm fast', 'B', 30, 'Sample player'),
  ('Aarav Iyer', 'men', 'Bowler', 'Left-hand bat', 'Right-arm fast', 'B', 30, 'Sample player'),
  ('Yash Gupta', 'men', 'Bowler', 'Right-hand bat', 'Right-arm fast', 'B', 30, 'Sample player'),
  ('Kavya Bhat', 'women', 'Batter', 'Right-hand bat', NULL, 'B', 20, 'Sample player'),
  ('Meera Shinde', 'women', 'Batter', 'Left-hand bat', 'Right-arm off-spin', 'B', 20, 'Sample player'),
  ('Isha Gupta', 'women', 'Wicket-keeper', 'Right-hand bat', NULL, 'C', 10, 'Sample player'),
  ('Meera Sharma', 'women', 'All-rounder', 'Left-hand bat', 'Right-arm medium', 'A', 30, 'Sample player'),
  ('Ananya Rao', 'women', 'Batter', 'Right-hand bat', NULL, 'B', 20, 'Sample player'),
  ('Meera Pawar', 'women', 'Batter', 'Left-hand bat', 'Right-arm off-spin', 'A', 30, 'Sample player'),
  ('Tara Kulkarni', 'women', 'Batter', 'Right-hand bat', NULL, 'C', 10, 'Sample player'),
  ('Isha Joshi', 'women', 'Wicket-keeper', 'Left-hand bat', NULL, 'C', 10, 'Sample player'),
  ('Riya Gupta', 'women', 'All-rounder', 'Left-hand bat', 'Right-arm medium', 'B', 20, 'Sample player'),
  ('Ananya Sharma', 'women', 'Batter', 'Left-hand bat', NULL, 'B', 20, 'Sample player'),
  ('Riya Patil', 'women', 'Bowler', 'Left-hand bat', 'Left-arm orthodox', 'C', 10, 'Sample player'),
  ('Sneha Deshpande', 'women', 'All-rounder', 'Right-hand bat', 'Right-arm off-spin', 'C', 10, 'Sample player'),
  ('Pooja Kale', 'women', 'Bowler', 'Right-hand bat', 'Right-arm leg-spin', 'B', 20, 'Sample player'),
  ('Isha Sharma', 'women', 'Batter', 'Left-hand bat', 'Right-arm off-spin', 'C', 10, 'Sample player'),
  ('Diya Rao', 'women', 'All-rounder', 'Left-hand bat', 'Left-arm orthodox', 'C', 10, 'Sample player'),
  ('Tara Joshi', 'women', 'All-rounder', 'Right-hand bat', 'Right-arm medium', 'A', 30, 'Sample player'),
  ('Meera Nair', 'women', 'Batter', 'Left-hand bat', 'Right-arm off-spin', 'B', 20, 'Sample player'),
  ('Kavya Sharma', 'women', 'Wicket-keeper', 'Right-hand bat', NULL, 'B', 20, 'Sample player'),
  ('Ananya Iyer', 'women', 'Bowler', 'Right-hand bat', 'Left-arm medium', 'B', 20, 'Sample player'),
  ('Sneha Shinde', 'women', 'Batter', 'Right-hand bat', NULL, 'B', 20, 'Sample player'),
  ('Priya Mehta', 'women', 'Batter', 'Right-hand bat', 'Right-arm off-spin', 'A', 30, 'Sample player'),
  ('Diya Mehta', 'women', 'Wicket-keeper', 'Left-hand bat', NULL, 'C', 10, 'Sample player'),
  ('Nisha Kale', 'women', 'Wicket-keeper', 'Right-hand bat', NULL, 'A', 30, 'Sample player'),
  ('Pooja Bhat', 'women', 'Bowler', 'Right-hand bat', 'Left-arm medium', 'B', 20, 'Sample player');
