-- Owner wishlists and push notifications.
--
-- Owners no longer bid from the app (the auctioneer enters every bid);
-- instead each team keeps a private wishlist of players it wants. When a
-- wishlisted player is put on the block, that team's owners get a push
-- notification. All three tables are private: browsers have no access, the
-- Next.js API reads and writes them with the service role and always scopes
-- wishlist reads/writes to the caller's own team.

create table public.wishlist (
  team_id     uuid not null references public.teams (id) on delete cascade,
  player_id   uuid not null references public.players (id) on delete cascade,
  -- 1 = must have, 2 = want, 3 = backup
  priority    smallint not null default 2 check (priority between 1 and 3),
  -- The most the team is willing to pay (a private target, not enforced).
  max_price   integer check (max_price >= 0),
  note        text check (char_length(note) <= 300),
  added_by    text not null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  primary key (team_id, player_id)
);
create index wishlist_player_idx on public.wishlist (player_id);

create trigger wishlist_touch before update on public.wishlist
  for each row execute function public.tg_touch_updated_at();

-- Web Push subscriptions (one per browser/device). Tied to the owner mapping,
-- so removing an owner also stops their notifications; the team is looked up
-- through owners at send time.
create table public.push_subscriptions (
  endpoint    text primary key check (char_length(endpoint) <= 1000),
  email       text not null references public.owners (email) on delete cascade,
  p256dh      text not null check (char_length(p256dh) <= 200),
  auth        text not null check (char_length(auth) <= 100),
  user_agent  text check (char_length(user_agent) <= 300),
  created_at  timestamptz not null default now()
);
create index push_subscriptions_email_idx on public.push_subscriptions (email);

-- Server-only settings generated by the app (the Web Push VAPID key pair is
-- created on first use, so there is nothing to configure).
create table public.app_secrets (
  name        text primary key,
  value       text not null,
  created_at  timestamptz not null default now()
);

alter table public.wishlist enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.app_secrets enable row level security;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all on public.wishlist from anon, authenticated;
    revoke all on public.push_subscriptions from anon, authenticated;
    revoke all on public.app_secrets from anon, authenticated;
  end if;
end $$;
